version: '3'
services:
  web:
    image: modx
    build:
      context: ./apache
      args:
        - MODX_VERSION
        - MODX_SHA1
    links:
      - 'db:mysql'
    ports:
      - '8000:80'
    environment:
      - MODX_VERSION
      - MODX_SHA1
      - MODX_DB_HOST
      - MODX_DB_PASSWORD
      - MODX_DB_USER
      - MODX_DB_NAME
      - MODX_LANGUAGE
    volumes:
      - './html:/var/www/html'
      - '/etc/localtime:/etc/localtime:ro'
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MODX_DB_NAME}"
      MYSQL_USER: "${MODX_DB_USER}"
      MYSQL_PASSWORD: "${MODX_DB_PASSWORD}"
    ports:
      - '3306:3306'
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - './mysql:/var/lib/mysql'
      - '/etc/localtime:/etc/localtime:ro'
